const state={step:1,data:{name:'',dob:'',time:'',place:'',situation:'',context:'',style:'A balanced mix',topics:[]},chart:null,geo:null};
const modal=document.getElementById('onboarding');const content=document.getElementById('formContent');const bar=document.getElementById('progressBar');
const situations=[['❤️','Struggling in love or relationships','Feeling disconnected, confused or uncertain.'],['💼','Working hard but not moving forward','Burnout, career uncertainty or stalled progress.'],['🔮','Unsure of my direction','Questioning your purpose or next chapter.'],['💰','Constant financial anxiety or instability','Wanting greater security or relief from money stress.'],['🧠','Feeling stuck in my own patterns','Overthinking, self-doubt or repeating behaviors.'],['🌱','Going through a major life change','A breakup, career shift, move or new chapter.'],['✦','Something else','Tell us what feels most important right now.']];
const topics=[['❤️','Love & Relationships','Connection, attraction, emotional patterns and partnership.'],['↗','Career & Work','Ambition, direction, work style and professional potential.'],['◌','Money & Financial Stability','Security, earning and long-term financial patterns.'],['☉','Personality & Emotions','Strengths, needs, emotions and inner wiring.'],['✺','Shadow & Growth','Blind spots, recurring patterns and personal evolution.'],['✧','Life Purpose','Meaning, direction and deeper themes.'],['🪐','Timing & Transits','Current cycles and the seasons ahead.']];
const styles=[['🌿','Gentle & reflective','Thoughtful, supportive and introspective.'],['🎯','Direct & honest','Clear insights without sugar-coating.'],['🔮','Deep & psychological','Focus on patterns, motivations and hidden dynamics.'],['⚡','Practical & actionable','Insights you can actually use.'],['✨','A balanced mix','A little of everything.']];
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const glyphs={Sun:'☉',Moon:'☾',Mercury:'☿',Venus:'♀',Mars:'♂',Jupiter:'♃',Saturn:'♄',Uranus:'♅',Neptune:'♆',Pluto:'♇'};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function open(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');state.step=1;render();setTimeout(()=>$('name')?.focus(),80)}
function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',open));$('closeModal')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});
function setProgress(){bar.style.width=`${Math.min(100,state.step/6*100)}%`}
function signAt(longitude){const lon=((longitude%360)+360)%360;const index=Math.floor(lon/30);return{index,name:signs[index],degree:lon-index*30,longitude:lon}}
function fmt(p){return `${p.degree.toFixed(1)}° ${p.name}`}
function localToUtc(dob,time,tz){const [y,m,d]=dob.split('-').map(Number);const [hh,mm]=time.split(':').map(Number);const guess=new Date(Date.UTC(y,m-1,d,hh,mm));const parts=new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(guess);const o={};parts.forEach(p=>o[p.type]=p.value);const localAsUtc=Date.UTC(+o.year,+o.month-1,+o.day,+o.hour,+o.minute);return new Date(guess.getTime()-(localAsUtc-guess.getTime()))}
async function geocode(place){const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(place)}`,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('Location lookup failed.');const rows=await r.json();if(!rows.length)throw Error('We could not find that birthplace. Try “City, Country”.');return{lat:+rows[0].lat,lon:+rows[0].lon,label:rows[0].display_name}}
function ascendant(date,lat,lon){const lst=((Astronomy.SiderealTime(date)*15+lon)%360+360)%360;const eps=23.4392911*Math.PI/180;const phi=lat*Math.PI/180;const th=lst*Math.PI/180;let a=Math.atan2(-Math.cos(th),Math.sin(th)*Math.cos(eps)+Math.tan(phi)*Math.sin(eps))*180/Math.PI;a=(a+180+360)%360;return signAt(a)}
function calculateChart(date,lat,lon,hasTime){const bodies=['Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn','Uranus','Neptune','Pluto'];const chart={date,latitude:lat,longitude:lon,placements:{}};for(const body of bodies)chart.placements[body]=signAt(Astronomy.EclipticLongitude(Astronomy.Body[body],date));chart.placements.Rising=hasTime?ascendant(date,lat,lon):null;chart.aspects=majorAspects(chart.placements);return chart}
function majorAspects(p){const names=Object.keys(p).filter(k=>k!=='Rising'&&p[k]);const targets=[['Conjunction',0,6],['Sextile',60,4],['Square',90,5],['Trine',120,5],['Opposition',180,6]];const out=[];for(let i=0;i<names.length;i++)for(let j=i+1;j<names.length;j++){let diff=Math.abs(p[names[i]].longitude-p[names[j]].longitude);diff=Math.min(diff,360-diff);for(const [name,angle,orb] of targets)if(Math.abs(diff-angle)<=orb){out.push({a:names[i],b:names[j],name,orb:+Math.abs(diff-angle).toFixed(1)});break}}return out.slice(0,8)}
function readingFor(topic,c){const p=c.placements;const sun=p.Sun,moon=p.Moon,venus=p.Venus,mars=p.Mars,jupiter=p.Jupiter,saturn=p.Saturn,rise=p.Rising;const rising=rise?` Your ${rise.name} Rising adds another layer to how you meet the world.`:'';const copy={'Love & Relationships':`Your ${venus.name} Venus describes how you tend to give and receive affection, while your ${moon.name} Moon speaks to emotional safety. With a ${sun.name} Sun, connection can become most meaningful when it feels both authentic and emotionally alive.${rising}`,'Career & Work':`Your ${sun.name} Sun points toward the kind of expression that keeps you engaged, while ${mars.name} Mars shows how you pursue goals. The chart suggests looking for work where your natural drive has room to become visible rather than forcing yourself into someone else’s definition of success.`, 'Money & Financial Stability':`Your ${venus.name} Venus and ${jupiter.name} Jupiter offer a reflection lens around comfort, opportunity and growth. ${saturn.name} Saturn adds the long-game lesson: stability tends to become stronger when desire is paired with structure.`,'Personality & Emotions':`Your ${sun.name} Sun is your central expression; your ${moon.name} Moon adds the private emotional layer.${rising} Together, these layers explain why you may sometimes look very different from how you feel inside.`,'Shadow & Growth':`Your ${saturn.name} Saturn can point toward lessons that become easier through maturity, while the ${moon.name} Moon can show emotional habits that run before conscious thought. The useful question is not “what is wrong with me?” but “what pattern am I ready to stop repeating?”`,'Life Purpose':`Your ${sun.name} Sun is the central thread of self-expression. ${mars.name} Mars adds clues about how you move toward meaningful goals. Purpose is better treated as a direction you develop than a single destiny you have to discover.`};return copy[topic]||`Your chart combines a ${sun.name} Sun and ${moon.name} Moon. This becomes the foundation for a deeper ${topic.toLowerCase()} reading.`}
function render(){setProgress();const d=state.data,c=state.chart;
if(state.step===1)content.innerHTML=`<div class="form-eyebrow">01 · YOUR BIRTH DATA</div><h2 class="form-title" id="modal-title">Let's start with the sky you were born under.</h2><p class="form-copy">Your birth details create the foundation of your personal chart.</p><div class="field"><label>Your name</label><input id="name" value="${esc(d.name)}" placeholder="What should we call you?" autocomplete="name"></div><div class="field"><label>Date of birth</label><input id="dob" type="date" value="${d.dob}"></div><div class="field"><label>Exact birth time <span class="muted">(recommended)</span></label><input id="time" type="time" value="${d.time}"><p class="form-copy">Your Rising sign and houses need an accurate birth time. You can continue without it.</p></div><div class="field"><label>Birthplace</label><input id="place" value="${esc(d.place)}" placeholder="City, country" autocomplete="address-level2"></div><div class="form-actions"><span></span><button class="primary-btn" id="next">Continue →</button></div>`;
else if(state.step===2)content.innerHTML=`<div class="form-eyebrow">02 · YOUR CONTEXT · OPTIONAL</div><h2 class="form-title">What's happening in your life right now?</h2><p class="form-copy">A little context helps the reading feel more personal. Or skip it.</p><div class="choice-grid">${situations.map((x,i)=>`<button class="choice ${d.situation===x[1]?'selected':''}" data-sit="${i}"><strong>${x[0]} ${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div><div class="field"><label>Any specific details? <span class="muted">(optional)</span></label><textarea id="context" placeholder="A few words about what's on your mind…">${esc(d.context)}</textarea></div><div class="form-actions"><button class="back-btn" id="back">← Back</button><div><button class="skip" id="skip">Skip</button><button class="primary-btn" id="next">Continue →</button></div></div>`;
else if(state.step===3)content.innerHTML=`<div class="form-eyebrow">03 · YOUR READING STYLE</div><h2 class="form-title">How do you want your reading to feel?</h2><p class="form-copy">Choose the voice that will help you most.</p><div class="choice-grid">${styles.map(x=>`<button class="choice ${d.style===x[1]?'selected':''}" data-style="${x[1]}"><strong>${x[0]} ${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div><div class="form-actions"><button class="back-btn" id="back">← Back</button><button class="primary-btn" id="next">Continue →</button></div>`;
else if(state.step===4)content.innerHTML=`<div class="form-eyebrow">04 · WHAT MATTERS TO YOU</div><h2 class="form-title">What do you want to understand?</h2><p class="form-copy"><strong>${d.topics.length}/3 selected</strong> · Choose up to three.</p><div class="choice-grid">${topics.map((x,i)=>`<button class="choice ${d.topics.includes(x[1])?'selected':''}" data-topic="${i}"><strong>${x[0]} ${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div><div class="form-actions"><button class="back-btn" id="back">← Back</button><button class="primary-btn" id="next">Calculate my chart ✦</button></div>`;
else if(state.step===5)content.innerHTML=`<div class="form-eyebrow">05 · CALCULATING YOUR CHART</div><h2 class="form-title">The sky is coming into focus.</h2><p class="form-copy" id="calcStatus">Finding your birthplace and calculating planetary positions…</p><div class="chart-loader">☾ <span>✦</span> ☉ <span>✧</span></div><div class="form-actions"><button class="back-btn" id="back">← Back</button><button class="primary-btn" id="finish" disabled>Preparing reading…</button></div>`;
else renderResult() ;bind()}
function renderResult(){const d=state.data,c=state.chart;const big=[['☉','SUN',c.placements.Sun],['☾','MOON',c.placements.Moon],['↑','RISING',c.placements.Rising]];const cards=d.topics.map(t=>{const meta=topics.find(x=>x[1]===t);return`<article class="free-reading-card"><span>${meta?.[0]||'✦'}</span><h3>${esc(t)}</h3><p>${esc(readingFor(t,c))}</p><div class="locked-line">✦ Deeper chart analysis · houses · aspects · timing</div></article>`}).join('');content.innerHTML=`<div class="result-header"><div class="form-eyebrow">YOUR AURAVIE READING</div><h2 class="form-title">The first layer is yours, ${esc(d.name||'stargazer')}.</h2><p class="form-copy">Calculated from ${esc(d.dob)} in ${esc(c.geoLabel.split(',')[0])}. ${d.time?'Exact birth time used.':'Birth time not provided, so Rising sign and houses are unavailable.'}</p></div><div class="preview-result">${big.map(x=>`<div><small>${x[0]} ${x[1]}</small><strong>${x[2]?x[2].name:'—'}</strong><span>${x[2]?fmt(x[2]):'Exact time needed'}</span></div>`).join('')}</div><div class="chart-stats"><span>✦ ${Object.keys(c.placements).length-1} planetary placements</span><span>✦ ${c.aspects.length} major aspects detected</span><span>✦ ${d.topics.length} personalized themes</span></div><div class="free-reading-list">${cards}</div><div class="premium-tease"><div><div class="form-eyebrow">FULL READING</div><h3>Your chart has more to say.</h3><p>Detailed planetary placements, houses, aspects, shadow patterns, timing and a longer personalized report are next.</p></div><button class="primary-btn" id="premium" type="button">Coming next · Full reading</button></div><p class="disclaimer">Astrology is for reflection, curiosity and self-discovery. It is not medical, legal or financial advice.</p><button class="back-btn" id="closeResult">← Return to Auravie</button>`}
async function prepareChart(){const status=$('calcStatus'),finish=$('finish');try{status.textContent='Finding your birthplace…';state.geo=await geocode(state.data.place);const tz=tzlookup(state.geo.lat,state.geo.lon);status.textContent=`Found ${state.geo.label.split(',').slice(0,2).join(', ')} · calculating the sky…`;const date=state.data.time?localToUtc(state.data.dob,state.data.time,tz):new Date(`${state.data.dob}T12:00:00Z`);state.chart=calculateChart(date,state.geo.lat,state.geo.lon,Boolean(state.data.time));state.chart.geoLabel=state.geo.label;state.chart.timezone=tz;status.textContent='Natal chart calculated ✓';finish.disabled=false;finish.textContent='See my free reading →';finish.onclick=()=>{state.step=6;render()}}catch(e){status.textContent=e.message||'Something went wrong. Please try again.';finish.disabled=false;finish.textContent='Try again';finish.onclick=prepareChart}}
function bind(){
$('next')?.addEventListener('click',async()=>{if(state.step===1){state.data.name=$('name').value.trim();state.data.dob=$('dob').value;state.data.time=$('time').value;state.data.place=$('place').value.trim();if(!state.data.dob||!state.data.place){alert('Please add your date of birth and birthplace.');return}state.step=2;render()}else if(state.step===2){state.data.context=$('context')?.value.trim()||'';state.step=3;render()}else if(state.step===3){state.step=4;render()}else if(state.step===4){if(!state.data.topics.length){alert('Choose at least one topic.');return}state.step=5;render();prepareChart()}});
$('back')?.addEventListener('click',()=>{state.step=Math.max(1,state.step-1);render()});$('skip')?.addEventListener('click',()=>{state.step=3;render()});$('closeResult')?.addEventListener('click',close);$('premium')?.addEventListener('click',()=>{const b=$('premium');b.textContent='Full reports are coming next ✦';b.disabled=true});
document.querySelectorAll('[data-sit]').forEach(b=>b.addEventListener('click',()=>{state.data.situation=situations[+b.dataset.sit][1];render()}));document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>{state.data.style=b.dataset.style;render()}));document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{const topic=topics[+b.dataset.topic][1];if(state.data.topics.includes(topic))state.data.topics=state.data.topics.filter(x=>x!==topic);else if(state.data.topics.length<3)state.data.topics.push(topic);render()}));}
